
name: Create ZIP and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          mkdir -p ${{ github.event.repository.name }}
          rsync -av --progress ./ ${{ github.event.repository.name }}/ --exclude .git --exclude .github
          zip -r ${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }}

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
