
name: Create Module ZIP and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   

    steps:

      - uses: actions/checkout@v4

      - name: Create ZIP archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'QuietKill224-${{ github.ref_name }}.zip'
          exclusions: | 
            *.git*
            *.github*
            *.gitignore


      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: QuietKill224-${{ github.ref_name }}.zip
