name: Build Magisk Module with Hash

on:
  release:
    types: [published]      # Сработает только когда вы опубликуете релиз через интерфейс GitHub

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate hash file
        run: |
          find . -type f \
            ! -path './.git/*' \
            ! -name '.gitignore' \
            ! -name '*.yml' \
            ! -name 'hash' \
            -printf '%P\0' | while IFS= read -r -d '' file; do
              sha256sum "$file" | awk '{print $2 "|" $1}'
          done > hash
          echo "Hash file generated"

      - name: Create Magisk ZIP
        run: |
          zip -r QuiteKill-${{ github.ref_name }}.zip . \
            -x '*.git*' \
            -x '.github/*' \
            -x '.gitignore' \
            -x '*.yml'

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: QuiteKill-${{ github.ref_name }}.zip
