name: Build Magisk Module

on:
  release:
    types: [published]   # Важно! Не используйте workflow_dispatch для загрузки в релиз

permissions:
  contents: write        # Глобальные права

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r QuietKill224-${{ github.ref_name }}.zip . \
            -x '*.git*' '*.github/*' '.gitignore' '*.yml'

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: QuietKill224-${{ github.ref_name }}.zip
